- name: Launch 3 local VMs using Multipass
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vm_count: 2
    base_name: "ansible-vm"
    image: 22.04
    memory: 1G
    disk: 3G
    cpus: 1

  tasks:
    - name: Launch Multipass VMs
      ansible.builtin.command: >
        multipass launch {{ image }}
        --name {{ base_name }}-{{ item }}
        --memory {{ memory }} --disk {{ disk }} --cpus {{ cpus }}
      loop: "{{ range(1, vm_count + 1) | list }}"